# Generated by Django 5.2.7 on 2026-07-10 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('practice_type', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('question_count', models.IntegerField(default=5)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('interview_goal', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('programming_language', models.CharField(max_length=50)),
                ('starter_code', models.TextField()),
                ('test_cases', models.JSONField(blank=True, default=list)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('optimal_solution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='coding.codingsession')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems_solved', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('languages_used', models.JSONField(blank=True, default=list)),
                ('top_skills', models.JSONField(blank=True, default=list)),
                ('weak_skills', models.JSONField(blank=True, default=list)),
                ('readiness_score', models.IntegerField(default=50)),
                ('xp', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_code', models.TextField()),
                ('programming_language', models.CharField(max_length=50)),
                ('passed_test_cases', models.IntegerField(default=0)),
                ('total_test_cases', models.IntegerField(default=0)),
                ('execution_time', models.FloatField(default=0.0)),
                ('memory_used', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('ai_review', models.JSONField(blank=True, default=dict)),
                ('follow_up_questions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='coding.generatedquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HintUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hints_used', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.generatedquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
