# Generated by Django 6.0.7 on 2026-07-08 07:07

import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('badge_icon', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('preferred_theme', models.CharField(default='default', max_length=50)),
                ('interview_difficulty', models.CharField(default='Intermediate', max_length=50)),
                ('preferred_roles', models.JSONField(blank=True, default=list, validators=[users.validators.validate_json_string_list])),
                ('preferred_companies', models.JSONField(blank=True, default=list, validators=[users.validators.validate_json_string_list])),
                ('language', models.CharField(default='English', max_length=50)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('current_role', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('preferred_job_role', models.CharField(blank=True, max_length=100)),
                ('preferred_company', models.CharField(blank=True, max_length=100)),
                ('preferred_interview_language', models.CharField(blank=True, max_length=50)),
                ('target_package', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('graduation_year', models.IntegerField(blank=True, null=True, validators=[users.validators.validate_graduation_year])),
                ('cgpa', models.FloatField(blank=True, null=True, validators=[users.validators.validate_cgpa])),
                ('skills', models.JSONField(blank=True, default=list, validators=[users.validators.validate_json_string_list])),
                ('interests', models.JSONField(blank=True, default=list, validators=[users.validators.validate_json_string_list])),
                ('github_url', models.URLField(blank=True, validators=[users.validators.validate_github_profile_url])),
                ('linkedin_url', models.URLField(blank=True, validators=[users.validators.validate_linkedin_profile_url])),
                ('portfolio_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('profile_completion_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_interviews', models.IntegerField(default=0)),
                ('completed_interviews', models.IntegerField(default=0)),
                ('coding_attempts', models.IntegerField(default=0)),
                ('coding_passed', models.IntegerField(default=0)),
                ('resumes_uploaded', models.IntegerField(default=0)),
                ('chatbot_questions', models.IntegerField(default=0)),
                ('roadmap_completed', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('highest_score', models.FloatField(default=0.0)),
                ('current_streak', models.IntegerField(default=0)),
                ('total_learning_hours', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earners', to='users.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
