# Generated by Django 6.0.7 on 2026-07-08 09:34

import django.db.models.deletion
import roadmap.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide or Heroicon name tag', max_length=100)),
                ('estimated_duration', models.CharField(help_text='e.g. 6 Months', max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Path',
                'verbose_name_plural': 'Career Paths',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('estimated_duration', models.CharField(max_length=100)),
                ('total_modules', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='roadmap.careerpath')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LearningReminder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reminder_time', models.TimeField(validators=[roadmap.validators.validate_reminder_time])),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='roadmap.roadmap')),
            ],
            options={
                'verbose_name': 'Learning Reminder',
                'verbose_name_plural': 'Learning Reminders',
                'ordering': ['reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapModule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('module_order', models.IntegerField(default=1)),
                ('estimated_hours', models.IntegerField(default=1)),
                ('module_type', models.CharField(choices=[('Video', 'Video'), ('Article', 'Article'), ('Practice', 'Practice'), ('Interview', 'Interview'), ('Coding', 'Coding'), ('Quiz', 'Quiz'), ('Project', 'Project')], default='Video', max_length=50)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='roadmap.roadmap')),
            ],
            options={
                'verbose_name': 'Roadmap Module',
                'verbose_name_plural': 'Roadmap Modules',
                'ordering': ['module_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('YouTube', 'YouTube'), ('Documentation', 'Documentation'), ('Course', 'Course'), ('Article', 'Article'), ('Book', 'Book'), ('GitHub', 'GitHub'), ('Website', 'Website'), ('Practice', 'Practice')], default='Website', max_length=50)),
                ('provider', models.CharField(blank=True, max_length=150)),
                ('url', models.URLField()),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('is_free', models.BooleanField(default=True)),
                ('roadmap_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='roadmap.roadmapmodule')),
            ],
            options={
                'verbose_name': 'Learning Resource',
                'verbose_name_plural': 'Learning Resources',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserRoadmap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('progress_percentage', models.FloatField(default=0.0, validators=[roadmap.validators.validate_percentage_range])),
                ('completed_modules', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Paused', 'Paused')], default='Not Started', max_length=50)),
                ('current_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_roadmaps', to='roadmap.roadmapmodule')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='roadmap.roadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Roadmap',
                'verbose_name_plural': 'User Roadmaps',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('roadmap_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='roadmap.roadmapmodule')),
                ('user_roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progresses', to='roadmap.userroadmap')),
            ],
            options={
                'verbose_name': 'Module Progress',
                'verbose_name_plural': 'Module Progresses',
                'unique_together': {('user_roadmap', 'roadmap_module')},
            },
        ),
    ]
