# Generated by Django 5.2.7 on 2026-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprogress',
            name='coding_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='quiz_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmapmodule',
            name='coding_questions_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmapmodule',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='roadmapmodule',
            name='interview_questions_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmapmodule',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roadmapmodule',
            name='projects_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmapmodule',
            name='quiz_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
