# Generated by Django 5.2.7 on 2026-07-17 07:20

import roadmap.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_roadmappathway_roadmapmilestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapmilestone',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roadmapmilestone',
            name='progress_percent',
            field=models.IntegerField(default=0, help_text="User's progress through this milestone (0-100%)", validators=[roadmap.validators.validate_percentage_range]),
        ),
        migrations.AlterField(
            model_name='roadmappathway',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roadmappathway',
            name='overall_readiness_estimate_percent',
            field=models.IntegerField(default=0, help_text='Estimated readiness % for the goal (0-100)'),
        ),
        migrations.AlterField(
            model_name='roadmappathway',
            name='user_interest_text',
            field=models.TextField(help_text="What user stated they want to become/learn (e.g., 'QA Engineer')"),
        ),
    ]
