# Generated by Django 5.2.7 on 2026-07-14 08:40

import chatbot.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('USER', 'USER'), ('BOT', 'BOT')], default='USER', max_length=10)),
                ('message', models.TextField(validators=[chatbot.validators.validate_message_length])),
                ('response_source', models.CharField(blank=True, choices=[('LOCAL', 'LOCAL'), ('GEMINI', 'GEMINI'), ('GROK', 'GROK'), ('OLLAMA', 'OLLAMA')], max_length=10, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[chatbot.validators.validate_rating])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Feedback',
                'verbose_name_plural': 'Chat Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('keywords', models.TextField(help_text='Comma-separated keywords')),
                ('synonyms', models.TextField(blank=True, help_text='Comma-separated synonyms')),
                ('priority', models.IntegerField(default=0)),
                ('difficulty', models.CharField(default='Medium', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='chatbot.category')),
            ],
            options={
                'verbose_name': 'Knowledge Base Entry',
                'verbose_name_plural': 'Knowledge Base Entries',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAnalytics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('was_matched', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('response_source', models.CharField(default='GEMINI', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_knowledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_hits', to='chatbot.knowledgebase')),
            ],
            options={
                'verbose_name': 'Admin Analytics Record',
                'verbose_name_plural': 'Admin Analytics Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
