# Generated by Django 6.0.7 on 2026-07-08 09:07

import django.db.models.deletion
import feedback.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evaluation_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interviews.interviewsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(validators=[feedback.validators.validate_feedback_length])),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=50, validators=[feedback.validators.validate_suggestion_priority])),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='feedback.interviewevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='HRBehaviorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('professionalism_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('leadership_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('teamwork_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('adaptability_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('attitude_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('behavioral_feedback', models.TextField(blank=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_evaluation', to='feedback.interviewevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='feedback.interviewevaluation')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('grammar_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('fluency_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('vocabulary_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('clarity_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('pronunciation_score_placeholder', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('confidence_score_placeholder', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_evaluation', to='feedback.interviewevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='OverallEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('overall_rating', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Needs Improvement', 'Needs Improvement')], default='Average', max_length=50)),
                ('recommendation', models.CharField(blank=True, max_length=255)),
                ('final_feedback', models.TextField(blank=True)),
                ('next_learning_plan', models.TextField(blank=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overall_evaluation', to='feedback.interviewevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('YouTube', 'YouTube'), ('Documentation', 'Documentation'), ('Article', 'Article'), ('Course', 'Course'), ('Book', 'Book'), ('Practice Set', 'Practice Set')], default='Course', max_length=50)),
                ('url', models.URLField(validators=[feedback.validators.validate_resource_url])),
                ('description', models.TextField(blank=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='feedback.interviewevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('coding_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('problem_solving_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('database_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('algorithm_score', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('explanation_quality', models.IntegerField(default=0, validators=[feedback.validators.validate_score_range])),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_evaluation', to='feedback.interviewevaluation')),
            ],
        ),
    ]
