# Generated by Django 5.2.7 on 2026-07-11 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=20)),
                ('interview_mode', models.CharField(max_length=20)),
                ('selected_skills', models.JSONField(default=list)),
                ('score_goal', models.IntegerField(default=85)),
                ('total_questions', models.IntegerField(default=5)),
                ('ready_score', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('scenario_context', models.TextField(blank=True)),
                ('skill_focus', models.JSONField(default=list)),
                ('difficulty_tag', models.CharField(max_length=20)),
                ('expected_answer_points', models.JSONField(default=list)),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('ai_score', models.IntegerField(null=True)),
                ('ai_feedback', models.JSONField(default=dict, null=True)),
                ('status', models.CharField(default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='nlp.interviewsession')),
            ],
        ),
    ]
