# Generated by Django 5.2.7 on 2026-07-11 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_coachchatsession_coachchatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('extracted_text', models.TextField()),
                ('target_role', models.CharField(blank=True, max_length=100, null=True)),
                ('overall_ats_score', models.IntegerField()),
                ('category_scores', models.JSONField(default=dict)),
                ('keyword_analysis', models.JSONField(default=dict)),
                ('formatting_issues', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('detected_sections', models.JSONField(default=list)),
                ('missing_sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
