# Generated by Django 6.0.7 on 2026-07-08 07:58

import django.db.models.deletion
import interviews.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('target_role', models.CharField(max_length=255)),
                ('target_company', models.CharField(max_length=255)),
                ('interview_type', models.CharField(choices=[('HR', 'HR'), ('Technical', 'Technical'), ('Coding', 'Coding'), ('Mixed', 'Mixed'), ('Custom', 'Custom')], max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50)),
                ('interview_mode', models.CharField(choices=[('Text', 'Text'), ('Voice', 'Voice')], max_length=50)),
                ('language', models.CharField(default='English', max_length=100)),
                ('total_questions', models.IntegerField(validators=[interviews.validators.validate_question_count])),
                ('answered_questions', models.IntegerField(default=0)),
                ('current_question_index', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(validators=[interviews.validators.validate_duration_range])),
                ('elapsed_time_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused')], default='Scheduled', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.IntegerField(default=0)),
                ('communication_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('grammar_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('feedback_placeholder', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='interviews.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50)),
                ('sequence_number', models.IntegerField()),
                ('source', models.CharField(choices=[('Database', 'Database'), ('AI', 'AI'), ('Manual', 'Manual')], default='Database', max_length=50)),
                ('expected_answer_placeholder', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='InterviewProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_completed', models.FloatField(default=0.0)),
                ('remaining_questions', models.IntegerField(default=0)),
                ('elapsed_time', models.IntegerField(default=0)),
                ('estimated_remaining_time', models.IntegerField(default=0)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.interviewquestion')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='interviews.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answer_type', models.CharField(choices=[('Text', 'Text'), ('Voice', 'Voice')], default='Text', max_length=50)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='answers_audio/', validators=[interviews.validators.validate_audio_file_size])),
                ('answer_duration', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviews.interviewquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviews.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='interviews.interviewsession')),
            ],
        ),
    ]
