# Generated by Django 5.2.7 on 2026-07-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='feedback',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='adaptive_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
