# Generated by Django 5.2.7 on 2026-07-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewanswer_feedback_interviewanswer_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
