# Generated by Django 6.0.7 on 2026-07-08 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resumes/')),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('resume_version', models.IntegerField(default=1)),
                ('resume_text', models.TextField(blank=True)),
                ('total_pages', models.IntegerField(default=1)),
                ('upload_source', models.CharField(default='Web', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('processing_status', models.CharField(default='Pending', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0)),
                ('ats_score', models.IntegerField(default=0)),
                ('grammar_score', models.IntegerField(default=0)),
                ('keyword_score', models.IntegerField(default=0)),
                ('completeness_score', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('recommended_roles', models.JSONField(blank=True, default=list)),
                ('analysis_status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='resume.resume')),
            ],
        ),
    ]
