# Generated by Django 6.0.7 on 2026-07-08 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_name', models.CharField(choices=[('Ollama', 'Ollama'), ('Gemini', 'Gemini'), ('OpenAI', 'OpenAI')], max_length=100, unique=True)),
                ('provider_type', models.CharField(max_length=50)),
                ('base_url', models.URLField(blank=True)),
                ('model_name', models.CharField(max_length=150)),
                ('api_key_reference', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('max_tokens', models.IntegerField(default=2048)),
                ('timeout', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'ordering': ['provider_name'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=150)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('model_type', models.CharField(choices=[('Chat', 'Chat'), ('Embedding', 'Embedding'), ('Speech', 'Speech')], default='Chat', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('context_window', models.IntegerField(default=4096)),
                ('supports_streaming', models.BooleanField(default=True)),
                ('supports_function_calling', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_core.aiprovider')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
                ('request_type', models.CharField(choices=[('Chat', 'Chat'), ('Resume Parsing', 'Resume Parsing'), ('Question Generation', 'Question Generation'), ('Answer Evaluation', 'Answer Evaluation'), ('Speech Transcription', 'Speech Transcription'), ('Roadmap Recommendation', 'Roadmap Recommendation')], default='Chat', max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=150)),
                ('prompt_length', models.IntegerField(default=0)),
                ('response_length', models.IntegerField(default=0)),
                ('execution_time', models.FloatField(default=0.0)),
                ('token_usage', models.IntegerField(default=0)),
                ('request_status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Success', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Request Log',
                'verbose_name_plural': 'AI Request Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageStatistics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_requests', models.IntegerField(default=0)),
                ('embedding_requests', models.IntegerField(default=0)),
                ('llm_requests', models.IntegerField(default=0)),
                ('whisper_requests', models.IntegerField(default=0)),
                ('qdrant_searches', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Statistics',
                'verbose_name_plural': 'AI Usage Statistics',
            },
        ),
    ]
