# Generated by Django 5.2.7 on 2026-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='provider_name',
            field=models.CharField(choices=[('Ollama', 'Ollama'), ('Gemini', 'Gemini'), ('OpenAI', 'OpenAI'), ('Groq', 'Groq')], max_length=100, unique=True),
        ),
    ]
